import '../domain/repositories/admin_customers_port.dart';

/// Turns a user-typed search term into the `ILIKE` pattern PostgREST applies.
///
/// The term is escaped for LIKE metacharacters first: PostgreSQL's default
/// LIKE escape character is a backslash, and without this a search for `%`
/// stands in for "any run of characters" — typing it would return the entire
/// table instead of narrowing it. The surrounding `%` are the actual
/// substring wildcards we want.
String customerSearchPattern(String term) {
  final escaped = term
      .replaceAll(r'\', r'\\')
      .replaceAll('%', r'\%')
      .replaceAll('_', r'\_');
  return '%$escaped%';
}

/// The whole alphabet a **phone-shaped** term is allowed to use: digits, plus
/// the `+ - . ( ) /` and space that separate them in a typed number.
///
/// Deliberately a small, closed set. Everything outside it is what makes a term
/// a literal search rather than a phone one (see [customerPhoneDigitPattern]),
/// and that is also why no character can be slipped past it and into the query.
///
/// ASCII-only because it is applied AFTER [_asciiDigits] has mapped the Arabic
/// digit ranges into it — so this set does not have to grow by 20 codepoints,
/// and cannot fall out of step with the migration's `translate` tables.
final RegExp _digitOrSeparator = RegExp(r'[0-9+\-.()/ ]');

/// The complement of "is a digit".
final RegExp _nonDigit = RegExp(r'[^0-9]');

/// Maps the digits of EVERY Unicode Nd (decimal digit) block onto their ASCII
/// equivalents, leaving every other character alone — not only the Arabic
/// ranges. Digit systems are not confined to Arabic script: Devanagari,
/// Thai, fullwidth, the Mathematical Alphanumeric digits and dozens more all
/// appear in user-typed text, and normalising only the ranges the author had
/// heard of would reproduce the same defect for the rest.
///
/// The block list is GENERATED by supabase/tests/gen_phone_digit_ranges.py
/// from the Unicode database (`unicodedata`), the same source that emits the
/// migration's `translate` tables — one source of truth, two runtimes. Every
/// Nd block is 10 codepoints starting at digit value 0, so a base plus a
/// position is the whole mapping.
///
/// Linear scans over a 75-entry sorted list: the search path is debounced and
/// the input is short, so the constant is irrelevant next to the network call
/// it feeds.
// unicode-digit-blocks:generated — do not edit by hand
// 75 non-ASCII Nd blocks, unicodedata 16.0.0; regenerate with
//   python3 supabase/tests/gen_phone_digit_ranges.py --apply
const List<int> _digitBlockBases = <int>[
  0x0660,
  0x06F0,
  0x07C0,
  0x0966,
  0x09E6,
  0x0A66,
  0x0AE6,
  0x0B66,
  0x0BE6,
  0x0C66,
  0x0CE6,
  0x0D66,
  0x0DE6,
  0x0E50,
  0x0ED0,
  0x0F20,
  0x1040,
  0x1090,
  0x17E0,
  0x1810,
  0x1946,
  0x19D0,
  0x1A80,
  0x1A90,
  0x1B50,
  0x1BB0,
  0x1C40,
  0x1C50,
  0xA620,
  0xA8D0,
  0xA900,
  0xA9D0,
  0xA9F0,
  0xAA50,
  0xABF0,
  0xFF10,
  0x104A0,
  0x10D30,
  0x10D40,
  0x11066,
  0x110F0,
  0x11136,
  0x111D0,
  0x112F0,
  0x11450,
  0x114D0,
  0x11650,
  0x116C0,
  0x116D0,
  0x116DA,
  0x11730,
  0x118E0,
  0x11950,
  0x11BF0,
  0x11C50,
  0x11D50,
  0x11DA0,
  0x11F50,
  0x16130,
  0x16A60,
  0x16AC0,
  0x16B50,
  0x16D70,
  0x1CCF0,
  0x1D7CE,
  0x1D7D8,
  0x1D7E2,
  0x1D7EC,
  0x1D7F6,
  0x1E140,
  0x1E2F0,
  0x1E4F0,
  0x1E5F1,
  0x1E950,
  0x1FBF0,
];
// unicode-digit-blocks:end

String _asciiDigits(String term) {
  final buffer = StringBuffer();
  for (final rune in term.runes) {
    var mapped = false;
    for (final base in _digitBlockBases) {
      final offset = rune - base;
      if (offset >= 0 && offset <= 9) {
        buffer.write(offset);
        mapped = true;
        break;
      }
    }
    if (!mapped) {
      buffer.writeCharCode(rune);
    }
  }
  return buffer.toString();
}

/// The `ILIKE` pattern for a **phone-shaped** [term], or `null` when the term
/// is not one.
///
/// `profiles.phone` stores whatever the customer typed, separators included
/// ('+966 50 123 4567'), while an admin searching for a customer types the
/// digits ('966501234567'). Comparing the two literally can never match, and
/// there is no normalisation on the way in. So the term is reduced to its
/// digits and matched against `profiles.phone_digits`, the generated column
/// (migration 065) that holds the stored number's digits.
///
/// **Digit-shaped is a strict test, not "contains a digit".** Every character
/// must be a digit or a phone separator, and there must be at least one digit.
/// Anything looser would reinterpret ordinary text as a phone query: `A1`
/// reduces to the digit `1`, which matches nearly every row's phone and turns a
/// typed name into a directory-wide result. Names may legitimately contain
/// digits (`Branch 2`), and those must keep matching through `full_name`.
///
/// No LIKE escaping is needed on the result, and that is structural rather than
/// an omission: the value is built by *removing* everything that is not `0-9`,
/// so `%`, `_` and `\` cannot survive into it. The surrounding `%` are ours.
/// Arabic-Indic digits are transliterated FIRST, and the order is load-bearing
/// rather than tidy: [_nonDigit] is `[^0-9]`, i.e. ASCII-only, so it does not
/// treat `٠١٢` as digits it should keep — it treats them as characters to
/// DELETE. An AR-locale admin typing native digits would otherwise reduce to
/// the empty string and fall back to a literal search that matches nothing.
///
/// Only the phone pattern is transliterated. The term's NAME branch stays
/// exactly as typed, because Arabic names are stored in Arabic script and must
/// be matched literally.
String? customerPhoneDigitPattern(String term) {
  final ascii = _asciiDigits(term);
  final digits = ascii.replaceAll(_nonDigit, '');
  if (digits.isEmpty) return null;
  if (ascii.replaceAll(_digitOrSeparator, '').isNotEmpty) return null;
  return '%$digits%';
}

/// Wraps [pattern] so PostgREST reads it as a literal value inside an `or`
/// tree, where a raw `,` would split one condition into two and `(`/`)`
/// re-group the tree. A quote inside the value is itself backslash-escaped so
/// it cannot close the wrapper early.
///
/// Applied to the digit pattern as well. That one cannot contain structure
/// today — it is built by removing every non-digit — but routing both clauses
/// through one wrapper means no future reader has to re-derive that to be sure.
String _literalInOrTree(String pattern) =>
    '"${pattern.replaceAll('"', r'\"')}"';

/// The PostgREST filter matching the directory's searchable columns for
/// [term]: the customer's name **or** their phone number.
///
/// Expressed as a single `or` tree because the two columns are alternates.
/// Chaining `.ilike('full_name', ...).ilike('phone', ...)` would AND them and
/// return only rows whose name *and* phone both contain the term, which for a
/// phone-shaped query is the empty set.
///
/// **The term is escaped twice, because it crosses two parsers.** The LIKE
/// stage ([customerSearchPattern]) neutralises `\`, `%` and `_`; the `or`-tree
/// stage ([_literalInOrTree]) neutralises what PostgREST reads as *structure*,
/// so a search for `Smith, John` cannot fail outright or silently query
/// something else.
///
/// The phone half is chosen by term shape via [customerPhoneDigitPattern]: a
/// phone-shaped term searches the normalised `phone_digits` column, everything
/// else searches `phone` literally. The two are alternatives rather than
/// cumulative on purpose — for a term that is nothing but digits, matching
/// `phone_digits` already subsumes matching `phone`, because a digit-only term
/// found inside the stored value sits on an unbroken run of digits and so
/// survives normalisation unchanged. Emitting both would be a redundant second
/// condition on every phone search.
///
/// This is the first place user-typed text reaches an `or` tree —
/// [customerKeysetFilter] is safe only because a UTC timestamp's alphabet has
/// no structural characters.
String customerSearchFilter(String term) {
  final digitPattern = customerPhoneDigitPattern(term);
  final phoneClause = digitPattern == null
      ? 'phone.ilike.${_literalInOrTree(customerSearchPattern(term))}'
      : 'phone_digits.ilike.${_literalInOrTree(digitPattern)}';
  final nameClause =
      'full_name.ilike.${_literalInOrTree(customerSearchPattern(term))}';
  return '$nameClause,$phoneClause';
}

/// The PostgREST filter that resumes a newest-first directory walk *after*
/// [cursor].
///
/// Spelled `created_at < ts OR (created_at = ts AND id < lastId)` — the rows
/// the previous page did not reach under the `(created_at DESC, id DESC)`
/// order this repository asks for, which is why the tie-breaking `id` clause
/// is not optional (see [customerCursorForRow]).
///
/// PostgREST reads everything after `column.operator.` as the value, so the
/// dots inside a timestamp are part of the value rather than further
/// separators — the same reason the canonical
/// `?created_at=gte.2024-01-01T00:00:00.000Z` works. The value is kept in UTC
/// with a `Z` suffix, so it can never contain a `,` or `)`, which *are*
/// structural inside an `or` tree.
String customerKeysetFilter(CustomerCursor cursor) =>
    'created_at.lt.${cursor.createdAt},'
    'and(created_at.eq.${cursor.createdAt},id.lt.${cursor.id})';

/// The keyset bookmark for [row], or null when that row cannot anchor a page.
///
/// Returns null for a row whose `created_at` is absent or unparseable, and the
/// caller reads that as the end of the list. Stopping is deliberate: resuming
/// from an unknown position could repeat or skip rows, which is the exact
/// defect this paging exists to remove. `profiles.created_at` is NOT NULL and
/// the select asks for it, so this is unreachable unless one of those two
/// facts changes.
CustomerCursor? customerCursorForRow(Map<String, dynamic> row) {
  final id = row['id'];
  final createdAt = row['created_at'];
  if (id is! String || id.isEmpty || createdAt is! String) return null;
  final parsed = DateTime.tryParse(createdAt);
  if (parsed == null) return null;
  // Normalised to UTC so the value is canonical and its alphabet stays
  // digits/`-`/`:`/`T`/`.`/`Z` — nothing structural inside the `or` filter
  // that [customerKeysetFilter] builds from it.
  return (createdAt: parsed.toUtc().toIso8601String(), id: id);
}
