import 'package:supabase_flutter/supabase_flutter.dart';

import '../../../../core/error/app_error.dart';
import '../../../../core/error/result.dart';
import '../../../../core/utils/safe_parse.dart';
import '../../../../shared/services/logger.dart';
import '../domain/entities/admin_catalog.dart';
import '../domain/entities/admin_coupon.dart';
import '../domain/entities/admin_customer.dart';
import '../domain/entities/admin_order.dart';
import '../domain/entities/admin_sales.dart';
import '../domain/entities/admin_variant.dart';
import '../domain/entities/low_stock_variant.dart';
import '../domain/repositories/admin_repository.dart';
import 'admin_mappers.dart';

/// Turns a user-typed search term into the `ILIKE` pattern PostgREST applies.
///
/// The term is escaped for LIKE metacharacters first: PostgreSQL's default
/// LIKE escape character is a backslash, and without this a search for `%`
/// stands in for "any run of characters" — typing it would return the entire
/// table instead of narrowing it. The surrounding `%` are the actual
/// substring wildcards we want.
String customerSearchPattern(String term) {
  final escaped = term
      .replaceAll(r'\', r'\\')
      .replaceAll('%', r'\%')
      .replaceAll('_', r'\_');
  return '%$escaped%';
}

/// The whole alphabet a **phone-shaped** term is allowed to use: digits, plus
/// the `+ - . ( ) /` and space that separate them in a typed number.
///
/// Deliberately a small, closed set. Everything outside it is what makes a term
/// a literal search rather than a phone one (see [customerPhoneDigitPattern]),
/// and that is also why no character can be slipped past it and into the query.
///
/// ASCII-only because it is applied AFTER [_asciiDigits] has mapped the Arabic
/// digit ranges into it — so this set does not have to grow by 20 codepoints,
/// and cannot fall out of step with the migration's `translate` tables.
final RegExp _digitOrSeparator = RegExp(r'[0-9+\-.()/ ]');

/// The complement of "is a digit".
final RegExp _nonDigit = RegExp(r'[^0-9]');

/// Maps the digits of EVERY Unicode Nd (decimal digit) block onto their ASCII
/// equivalents, leaving every other character alone — not only the Arabic
/// ranges. Digit systems are not confined to Arabic script: Devanagari,
/// Thai, fullwidth, the Mathematical Alphanumeric digits and dozens more all
/// appear in user-typed text, and normalising only the ranges the author had
/// heard of would reproduce the same defect for the rest.
///
/// The block list is GENERATED by supabase/tests/gen_phone_digit_ranges.py
/// from the Unicode database (`unicodedata`), the same source that emits the
/// migration's `translate` tables — one source of truth, two runtimes. Every
/// Nd block is 10 codepoints starting at digit value 0, so a base plus a
/// position is the whole mapping.
///
/// Linear scans over a 75-entry sorted list: the search path is debounced and
/// the input is short, so the constant is irrelevant next to the network call
/// it feeds.
// unicode-digit-blocks:generated — do not edit by hand
// 75 non-ASCII Nd blocks, unicodedata 16.0.0; regenerate with
//   python3 supabase/tests/gen_phone_digit_ranges.py --apply
const List<int> _digitBlockBases = <int>[
  0x0660,
  0x06F0,
  0x07C0,
  0x0966,
  0x09E6,
  0x0A66,
  0x0AE6,
  0x0B66,
  0x0BE6,
  0x0C66,
  0x0CE6,
  0x0D66,
  0x0DE6,
  0x0E50,
  0x0ED0,
  0x0F20,
  0x1040,
  0x1090,
  0x17E0,
  0x1810,
  0x1946,
  0x19D0,
  0x1A80,
  0x1A90,
  0x1B50,
  0x1BB0,
  0x1C40,
  0x1C50,
  0xA620,
  0xA8D0,
  0xA900,
  0xA9D0,
  0xA9F0,
  0xAA50,
  0xABF0,
  0xFF10,
  0x104A0,
  0x10D30,
  0x10D40,
  0x11066,
  0x110F0,
  0x11136,
  0x111D0,
  0x112F0,
  0x11450,
  0x114D0,
  0x11650,
  0x116C0,
  0x116D0,
  0x116DA,
  0x11730,
  0x118E0,
  0x11950,
  0x11BF0,
  0x11C50,
  0x11D50,
  0x11DA0,
  0x11F50,
  0x16130,
  0x16A60,
  0x16AC0,
  0x16B50,
  0x16D70,
  0x1CCF0,
  0x1D7CE,
  0x1D7D8,
  0x1D7E2,
  0x1D7EC,
  0x1D7F6,
  0x1E140,
  0x1E2F0,
  0x1E4F0,
  0x1E5F1,
  0x1E950,
  0x1FBF0,
];
// unicode-digit-blocks:end
String _asciiDigits(String term) {
  final buffer = StringBuffer();
  for (final rune in term.runes) {
    var mapped = false;
    for (final base in _digitBlockBases) {
      final offset = rune - base;
      if (offset >= 0 && offset <= 9) {
        buffer.write(offset);
        mapped = true;
        break;
      }
    }
    if (!mapped) {
      buffer.writeCharCode(rune);
    }
  }
  return buffer.toString();
}

/// The `ILIKE` pattern for a **phone-shaped** [term], or `null` when the term
/// is not one.
///
/// `profiles.phone` stores whatever the customer typed, separators included
/// ('+966 50 123 4567'), while an admin searching for a customer types the
/// digits ('966501234567'). Comparing the two literally can never match, and
/// there is no normalisation on the way in. So the term is reduced to its
/// digits and matched against `profiles.phone_digits`, the generated column
/// (migration 065) that holds the stored number's digits.
///
/// **Digit-shaped is a strict test, not "contains a digit".** Every character
/// must be a digit or a phone separator, and there must be at least one digit.
/// Anything looser would reinterpret ordinary text as a phone query: `A1`
/// reduces to the digit `1`, which matches nearly every row's phone and turns a
/// typed name into a directory-wide result. Names may legitimately contain
/// digits (`Branch 2`), and those must keep matching through `full_name`.
///
/// No LIKE escaping is needed on the result, and that is structural rather than
/// an omission: the value is built by *removing* everything that is not `0-9`,
/// so `%`, `_` and `\` cannot survive into it. The surrounding `%` are ours.
/// Arabic-Indic digits are transliterated FIRST, and the order is load-bearing
/// rather than tidy: [_nonDigit] is `[^0-9]`, i.e. ASCII-only, so it does not
/// treat `٠١٢` as digits it should keep — it treats them as characters to
/// DELETE. An AR-locale admin typing native digits would otherwise reduce to
/// the empty string and fall back to a literal search that matches nothing.
///
/// Only the phone pattern is transliterated. The term's NAME branch stays
/// exactly as typed, because Arabic names are stored in Arabic script and must
/// be matched literally.
String? customerPhoneDigitPattern(String term) {
  final ascii = _asciiDigits(term);
  final digits = ascii.replaceAll(_nonDigit, '');
  if (digits.isEmpty) return null;
  if (ascii.replaceAll(_digitOrSeparator, '').isNotEmpty) return null;
  return '%$digits%';
}

/// Wraps [pattern] so PostgREST reads it as a literal value inside an `or`
/// tree, where a raw `,` would split one condition into two and `(`/`)`
/// re-group the tree. A quote inside the value is itself backslash-escaped so
/// it cannot close the wrapper early.
///
/// Applied to the digit pattern as well. That one cannot contain structure
/// today — it is built by removing every non-digit — but routing both clauses
/// through one wrapper means no future reader has to re-derive that to be sure.
String _literalInOrTree(String pattern) =>
    '"${pattern.replaceAll('"', r'\"')}"';

/// The PostgREST filter matching the directory's searchable columns for
/// [term]: the customer's name **or** their phone number.
///
/// Expressed as a single `or` tree because the two columns are alternates.
/// Chaining `.ilike('full_name', ...).ilike('phone', ...)` would AND them and
/// return only rows whose name *and* phone both contain the term, which for a
/// phone-shaped query is the empty set.
///
/// **The term is escaped twice, because it crosses two parsers.** The LIKE
/// stage ([customerSearchPattern]) neutralises `\`, `%` and `_`; the `or`-tree
/// stage ([_literalInOrTree]) neutralises what PostgREST reads as *structure*,
/// so a search for `Smith, John` cannot fail outright or silently query
/// something else.
///
/// The phone half is chosen by term shape via [customerPhoneDigitPattern]: a
/// phone-shaped term searches the normalised `phone_digits` column, everything
/// else searches `phone` literally. The two are alternatives rather than
/// cumulative on purpose — for a term that is nothing but digits, matching
/// `phone_digits` already subsumes matching `phone`, because a digit-only term
/// found inside the stored value sits on an unbroken run of digits and so
/// survives normalisation unchanged. Emitting both would be a redundant second
/// condition on every phone search.
///
/// This is the first place user-typed text reaches an `or` tree —
/// [customerKeysetFilter] is safe only because a UTC timestamp's alphabet has
/// no structural characters.
String customerSearchFilter(String term) {
  final digitPattern = customerPhoneDigitPattern(term);
  final phoneClause = digitPattern == null
      ? 'phone.ilike.${_literalInOrTree(customerSearchPattern(term))}'
      : 'phone_digits.ilike.${_literalInOrTree(digitPattern)}';
  final nameClause =
      'full_name.ilike.${_literalInOrTree(customerSearchPattern(term))}';
  return '$nameClause,$phoneClause';
}

/// The PostgREST filter that resumes a newest-first directory walk *after*
/// [cursor].
///
/// Spelled `created_at < ts OR (created_at = ts AND id < lastId)` — the rows
/// the previous page did not reach under the `(created_at DESC, id DESC)`
/// order this repository asks for, which is why the tie-breaking `id` clause
/// is not optional (see `_customerCursor`).
///
/// PostgREST reads everything after `column.operator.` as the value, so the
/// dots inside a timestamp are part of the value rather than further
/// separators — the same reason the canonical
/// `?created_at=gte.2024-01-01T00:00:00.000Z` works. The value is kept in UTC
/// with a `Z` suffix, so it can never contain a `,` or `)`, which *are*
/// structural inside an `or` tree.
String customerKeysetFilter(CustomerCursor cursor) =>
    'created_at.lt.${cursor.createdAt},'
    'and(created_at.eq.${cursor.createdAt},id.lt.${cursor.id})';

/// The keyset bookmark for [row], or null when that row cannot anchor a page.
///
/// Returns null for a row whose `created_at` is absent or unparseable, and the
/// caller reads that as the end of the list. Stopping is deliberate: resuming
/// from an unknown position could repeat or skip rows, which is the exact
/// defect this paging exists to remove. `profiles.created_at` is NOT NULL and
/// the select asks for it, so this is unreachable unless one of those two
/// facts changes.
CustomerCursor? _customerCursor(Map<String, dynamic> row) {
  final id = row['id'];
  final createdAt = row['created_at'];
  if (id is! String || id.isEmpty || createdAt is! String) return null;
  final parsed = DateTime.tryParse(createdAt);
  if (parsed == null) return null;
  // Normalised to UTC so the value is canonical and its alphabet stays
  // digits/`-`/`:`/`T`/`.`/`Z` — nothing structural inside the `or` filter
  // that [customerKeysetFilter] builds from it.
  return (createdAt: parsed.toUtc().toIso8601String(), id: id);
}

/// Supabase-backed implementation of [AdminRepository].
///
/// The only place in the admin feature that knows about Supabase. Raw
/// rows/RPC payloads are mapped to typed entities by [AdminMappers] and
/// every failure is returned as `Result.failure` — no exceptions cross
/// the repository boundary.
final class SupabaseAdminRepository implements AdminRepository {
  SupabaseAdminRepository({SupabaseClient? client})
      : _client = client ?? Supabase.instance.client;

  final SupabaseClient _client;

  @override
  Future<bool> isCurrentUserAdmin() async {
    final user = _client.auth.currentUser;
    if (user == null) return false;
    try {
      final response = await _client
          .from('profiles')
          .select('is_admin')
          .eq('id', user.id)
          .single();
      return response['is_admin'] as bool? ?? false;
    } catch (e) {
      // A failed permission probe must not grant admin. Catches broadly
      // because malformed payloads raise TypeError (an Error, not an
      // Exception) that must never escape the repository boundary. Also why
      // this stays a hand-written `try`/`catch` — it answers with a bool
      // rather than a `Result`, and it logs before denying.
      // Logged via error: (never interpolated — probe payloads can carry
      // PII; audit 2026-09-14 P0-5).
      Log.w('Admin permission probe failed; denying admin.',
          category: LogCategory.auth, error: e);
      return false;
    }
  }

  // ─── Order Fulfillment ──────────────────────────────────

  /// Lists orders for the admin queue.
  ///
  /// RLS NOTE: the embedded `profiles(full_name)` is filtered by the
  /// caller's own profile policy, and `profiles` currently grants only
  /// `auth.uid() = id` — so an admin sees the orders but a NULL profile for
  /// other users, i.e. blank customer names. Until
  /// `supabase/migrations/_proposals/061_admin_profiles_read.sql` is applied,
  /// prefer [getOrderDetails] (RPC, RLS-bypassing, admin-checked) when the
  /// customer identity is required. The mapper degrades the missing profile
  /// to an empty name rather than throwing, which is why this shows up as a
  /// blank label instead of an error.
  @override
  Future<Result<List<AdminOrder>>> getAllOrders({
    AdminOrderStatus? status,
    int limit = 50,
  }) =>
      Result.guard(() async {
        final query = _client.from('orders').select('*, profiles(full_name)');
        final filtered =
            status != null ? query.eq('status', status.dbValue) : query;
        final rows =
            await filtered.order('placed_at', ascending: false).limit(limit);
        return (rows as List)
            .whereType<Map<String, dynamic>>()
            // Rows without a string id cannot be navigated to; skip them.
            .where((r) => r['id'] is String)
            .map(AdminMappers.orderFromRow)
            .toList();
      }, 'Failed to load orders');

  @override
  Future<Result<AdminOrder?>> getOrderDetails(String orderId) =>
      Result.guard(() async {
        // `get_order_details` (migration 017) is SECURITY DEFINER and verifies
        // owner/admin inside the function, so it can return the customer
        // profile. The previous embedded select
        // (`profiles(id, full_name, membership_tier)`) is subject to the
        // VIEWER's row-level security, and `profiles` only grants
        // `auth.uid() = id` (migration 002) — so the join came back null for
        // every other user's order and the admin lost the customer identity.
        final payload = await _client.rpc(
          'get_order_details',
          params: {'p_order_id': orderId},
        );
        final row = _orderRowFromRpc(payload);
        if (row == null) return null;
        return AdminMappers.orderDetailFromRow(row);
      }, 'Failed to load order');

  /// Reshapes the `get_order_details` payload
  /// (`{order: {...}, items: [...], customer: {...}}`) into the single row
  /// shape [AdminMappers.orderDetailFromRow] already understands
  /// (`orders` + `order_items` + `profiles`). Returns null when the RPC
  /// reports no order.
  static Map<String, dynamic>? _orderRowFromRpc(Object? payload) {
    final body = safeMap(payload);
    final order = body['order'];
    if (order is! Map) return null;
    // Copied, not mutated in place: the decoded payload must not be
    // altered under other readers.
    final row = Map<String, dynamic>.from(safeMap(order));
    final items = body['items'];
    row['order_items'] = items is List ? items : const <Object>[];
    final customer = body['customer'];
    // `customer` is only absent when the order has no profile row; the
    // mapper already degrades to a blank name in that case.
    if (customer is Map) row['profiles'] = safeMap(customer);
    return row;
  }

  @override
  Future<Result<void>> updateOrderStatus(
    String orderId,
    AdminOrderStatus status, {
    String? trackingNumber,
  }) async {
    // Pre-flight validation stays OUTSIDE the guard: it is a domain check with
    // its own message, not something the boundary should swallow and relabel.
    if (status == AdminOrderStatus.unknown) {
      return const Failure(AppError('Unknown order status'));
    }
    return Result.guard<void>(() async {
      await _client.rpc('update_order_status', params: {
        'p_order_id': orderId,
        'p_new_status': status.dbValue,
        'p_tracking_number': trackingNumber,
      });
    }, 'Failed to update order status');
  }

  @override
  Future<Result<List<LowStockVariant>>> getLowStockProducts({
    int threshold = 5,
  }) =>
      Result.guard(() async {
        final response = await _client
            .rpc('get_low_stock_products', params: {'p_threshold': threshold});
        return AdminMappers.lowStockVariantsFromRows(response as List<dynamic>);
      }, 'Failed to load low stock products');

  @override
  Future<Result<AdminSalesOverview>> getSalesOverview({int days = 14}) =>
      Result.guard(() async {
        // Read-only dashboard aggregation (#12): a single bounded select
        // over existing orders rows with the joined line-item columns the
        // detail query already uses. Client-side aggregation keeps the
        // schema untouched; the limit keeps a burst of orders from
        // stalling the dashboard (same bounded-read discipline as
        // [getAllProducts]).
        final now = DateTime.now();
        final firstDay = DateTime.utc(now.year, now.month, now.day).subtract(
          Duration(days: (days < 1 ? 1 : days) - 1),
        );
        final rows = await _client
            .from('orders')
            .select('id, status, total, placed_at, '
                'order_items(product_name, quantity)')
            .gte('placed_at', firstDay.toIso8601String())
            .order('placed_at')
            .limit(1000);
        return AdminMappers.salesOverviewFromRows(
          rows as List<dynamic>,
          days: days,
          now: now,
        );
      }, 'Failed to load sales overview');

  // ─── Variant Management ─────────────────────────────────

  @override
  Future<Result<void>> updateStock(String variantId, int newStock) =>
      Result.guard<void>(() async {
        await _client
            .from('product_variants')
            .update({'stock': newStock}).eq('id', variantId);
      }, 'Failed to update stock');

  // ─── Catalog Management (T1) ─────────────────────────────

  @override
  Future<Result<List<AdminProduct>>> getAllProducts() => Result.guard(() async {
        // Bounded like the storefront fetchProducts(limit: 100) so a large
        // products table cannot stall the admin list: first 100 rows by
        // name via an explicit range page (audit residual P4).
        final rows = await _client
            .from('products')
            .select('id, name, slug, description, composition, category_id, '
                'base_price, is_active, categories(name)')
            .order('name')
            .limit(100)
            .range(0, 99);
        return AdminMappers.productsFromRows(rows as List<dynamic>);
      }, 'Failed to load products');

  @override
  Future<Result<AdminProduct?>> getProductById(String productId) =>
      Result.guard(() async {
        final rows = await _client
            .from('products')
            .select('id, name, slug, description, composition, category_id, '
                'base_price, is_active, categories(name)')
            .eq('id', productId)
            .limit(1);
        final list = rows as List<dynamic>;
        if (list.isEmpty) return null;
        return AdminMappers.productsFromRows(list).first;
      }, 'Failed to load product');

  @override
  Future<Result<List<AdminCategory>>> getAllCategories() =>
      Result.guard(() async {
        final rows = await _client
            .from('categories')
            .select('id, name, is_active')
            .order('sort_order');
        return AdminMappers.categoriesFromRows(rows as List<dynamic>);
      }, 'Failed to load categories');

  @override
  Future<Result<String>> adminUpsertProduct({
    String? id,
    required String name,
    required String slug,
    String? description,
    String? composition,
    String? care,
    String? origin,
    int? widthCm,
    int? gsm,
    bool? sellByLength,
    double? minCutMeters,
    required String categoryId,
    required double basePrice,
    required bool isActive,
  }) =>
      Result.guard<String>(() async {
        final res = await _client.rpc('admin_upsert_product', params: {
          'p_id': id,
          'p_name': name,
          'p_slug': slug,
          'p_description': description,
          'p_composition': composition,
          'p_category_id': categoryId,
          'p_base_price': basePrice,
          'p_is_active': isActive,
          // §10 fabric attributes: only sent when set — the pre-051 RPC
          // rejects unknown named parameters.
          if (care != null) 'p_care': care,
          if (origin != null) 'p_origin': origin,
          if (widthCm != null) 'p_width_cm': widthCm,
          if (gsm != null) 'p_gsm': gsm,
          if (sellByLength != null) 'p_sell_by_length': sellByLength,
          if (minCutMeters != null) 'p_min_cut_meters': minCutMeters,
        });
        if (res is! String || res.isEmpty) {
          // An RPC that answers without the product id is a protocol
          // violation, not a transport error — but it is reported with the
          // same message the boundary uses, so the text stays byte-identical
          // and the empty payload rides along as the cause.
          throw StateError('admin_upsert_product returned no product id');
        }
        return res;
      }, 'Failed to save product');

  @override
  Future<Result<String>> adminUpsertVariant({
    required String productId,
    required String size,
    required String color,
    required int stock,
    double? priceOverride,
  }) =>
      Result.guard<String>(() async {
        final res = await _client.rpc('admin_upsert_variant', params: {
          'p_product_id': productId,
          'p_size': size,
          'p_color': color,
          'p_stock': stock,
          'p_price_override': priceOverride,
        });
        if (res is! String || res.isEmpty) {
          // Same protocol-violation shape as [adminUpsertProduct]: message
          // text unchanged, empty payload recorded as the cause.
          throw StateError('admin_upsert_variant returned no variant id');
        }
        return res;
      }, 'Failed to save variant');

  @override
  Future<Result<void>> adminSetProductImages(
          String productId, List<String> storagePaths) =>
      Result.guard<void>(() async {
        await _client.rpc('admin_set_product_images', params: {
          'p_product_id': productId,
          'p_paths': storagePaths,
        });
      }, 'Failed to save images');

  @override
  Future<Result<List<AdminVariant>>> getVariants(String productId) =>
      Result.guard(() async {
        final res = await _client
            .from('product_variants')
            .select()
            .eq('product_id', productId)
            .order('size');
        return AdminMappers.variantsFromRows(res as List);
      }, 'Failed to load variants');

  @override
  Future<Result<List<String>>> getProductImagePaths(String productId) =>
      Result.guard(() async {
        final res = await _client
            .from('product_images')
            .select('storage_path')
            .eq('product_id', productId)
            .order('sort_order');
        return AdminMappers.imagePathsFromRows(res as List);
      }, 'Failed to load images');

  @override
  Future<Result<void>> setMembershipTier(String profileId, String tier) =>
      Result.guard<void>(() async {
        await _client.rpc('admin_set_membership_tier', params: {
          'p_profile_id': profileId,
          'p_tier': tier,
        });
      }, 'Failed to update membership tier');

  // ─── Coupons (feature-batch §8) ─────────────────────────

  @override
  Future<Result<List<AdminCoupon>>> fetchCoupons() => Result.guard(() async {
        final rows = await _client
            .from('coupons')
            .select('id, code, discount_minor, description, active')
            .order('created_at', ascending: false);
        final list = rows as List<dynamic>;
        return list
            .map((row) => _couponFromRow(row as Map<String, dynamic>))
            .toList();
      }, 'Failed to fetch coupons');

  @override
  Future<Result<AdminCoupon>> createCoupon({
    required String code,
    required int discountMinor,
    String? description,
  }) =>
      Result.guard(() async {
        final row = await _client
            .from('coupons')
            .upsert({
              'code': code.trim().toUpperCase(),
              'discount_minor': discountMinor,
              if (description != null && description.isNotEmpty)
                'description': description,
            })
            .select('id, code, discount_minor, description, active')
            .single();
        return _couponFromRow(row);
      }, 'Failed to create coupon');

  @override
  Future<Result<void>> setCouponActive(String id, bool active) =>
      Result.guard<void>(() async {
        await _client.from('coupons').update({'active': active}).eq('id', id);
      }, 'Failed to update coupon');

  // ─── Customers (feature-batch §14) ─────────────────────

  /// Columns that exist on `public.profiles`.
  ///
  /// `email` is deliberately ABSENT: the column does not exist on
  /// `profiles` (the address lives in `auth.users`, which PostgREST does not
  /// expose), and requesting it made PostgREST answer with
  /// `42703 column profiles.email does not exist`. Because the failure was
  /// mapped to a `Failure`, the whole Customers screen rendered an error and
  /// no customer could ever be listed. `phone` is the real contact column.
  ///
  /// `created_at` is requested for **position, not display**: it is half of
  /// the keyset bookmark (see [customerKeysetFilter]) and no caller renders
  /// it.
  ///
  /// Paged (audit follow-up): one bounded page plus an exact `count`, reached
  /// by keyset cursor. The read stays bounded, but the 501st customer is now
  /// reachable and the UI can say how many it is not showing — the previous
  /// `.limit(500)` truncated the directory silently.
  @override
  Future<
      Result<
          ({
            List<AdminCustomer> customers,
            int? total,
            CustomerCursor? nextCursor,
          })>> fetchCustomers({
    String? query,
    CustomerCursor? cursor,
    int limit = defaultCustomersPageSize,
  }) async {
    // Deliberately hand-written rather than `Result.guard`: this boundary
    // logs the cause before mapping it (see below) and the guard helper has
    // no logging hook. Every other method in this repository delegates to
    // the shared boundary.
    try {
      final term = query?.trim() ?? '';
      var request = _client
          .from('profiles')
          .select('id, full_name, phone, membership_tier, created_at');
      if (term.isNotEmpty) {
        // Name *or* phone — see [customerSearchFilter]. ANDed with the cursor
        // filter below as a second `or` parameter, which PostgREST conjoins.
        request = request.or(customerSearchFilter(term));
      }
      if (cursor != null) {
        request = request.or(customerKeysetFilter(cursor));
      }
      // One row past the page is requested so "is there another page?" is
      // answered by the data itself instead of by comparing a running count
      // against `total`. The extra row is dropped before returning.
      final response = await request
          // `id` is the tiebreaker, not decoration: `created_at` is not
          // unique (a seed, a bulk import, or two signups in the same tick all
          // share it) and a non-total sort key lets Postgres order those ties
          // differently per query — which is how a row lands on two
          // consecutive pages, or on neither. Matches [customerKeysetFilter].
          .order('created_at', ascending: false)
          .order('id', ascending: false)
          .limit(limit + 1)
          // `.count()` sets `Prefer: count=exact`, so one round trip carries
          // both the page and the total matching the same filter. It is asked
          // for on every page because a single response carries both, but is
          // only *reported* on the first: a cursor narrows the counted filter,
          // so a continuation page's count is the rows remaining rather than
          // the rows that match.
          .count(CountOption.exact);
      // Total decode parity with getAllOrders: mistyped rows degrade to
      // skips (audit 2026-09-14 P0-3) — previously `rows as List` threw on
      // a malformed payload and `row as Map` threw per-row.
      //
      // Rows without a usable string id are dropped *before* the page is cut
      // to size: they cannot be navigated to, and a bookmark taken past them
      // is what keeps `nextCursor` describing a row that was actually
      // returned.
      final rows = (response.data as List)
          .whereType<Map<String, dynamic>>()
          .where((row) {
        final id = row['id'];
        return id is String && id.isNotEmpty;
      }).toList();
      final hasMore = rows.length > limit;
      final page = hasMore ? rows.sublist(0, limit) : rows;
      final nextCursor = hasMore ? _customerCursor(page.last) : null;
      final list = page
          .map((row) => AdminCustomer(
                id: safeString(row, 'id'),
                name: safeString(row, 'full_name'),
                phone: safeString(row, 'phone'),
                tier: safeString(row, 'membership_tier', fallback: 'standard'),
                isBlocked:
                    false, // no suspension flag in profiles (§14 read-only)
              ))
          .toList();
      return Success((
        customers: list,
        // Only the first page can report a total (see the port's doc comment
        // and `AdminCustomersCubit`, which preserves the value it already
        // has).
        total: cursor == null ? response.count : null,
        nextCursor: nextCursor,
      ));
    } catch (e) {
      // NOTE: this endpoint needs an admin SELECT policy on `profiles`
      // (see supabase/migrations/061_admin_profiles_read.sql).
      // Without it RLS limits the result to the caller's own row; the call
      // still succeeds, so the directory is simply short.
      Log.w('fetchCustomers failed', category: LogCategory.network, error: e);
      return Failure(AppError('Failed to fetch customers', cause: e));
    }
  }

  // ─── Review moderation (feature-batch §9) ───────────────

  @override
  Future<Result<List<({String id, String product, String text, int rating})>>>
      fetchPendingReviews() => Result.guard(() async {
            final rows = await _client
                .from('product_reviews')
                .select('id, product_id, text, rating')
                .eq('status', 'pending')
                .order('created_at', ascending: false)
                .limit(100);
            // Total decode parity with fetchCustomers: mistyped rows degrade to
            // skips instead of one malformed review failing the whole pending
            // queue. Rows without a usable id/product_id cannot be moderated or
            // navigated to, so they are skipped.
            final list = (rows as List)
                .whereType<Map<String, dynamic>>()
                .where(
                    (row) => row['id'] is String && row['product_id'] is String)
                .map((row) => (
                      id: row['id'] as String,
                      product: row['product_id'] as String,
                      text: safeString(row, 'text'),
                      rating: safeInt(row, 'rating'),
                    ))
                .toList();
            return list;
          }, 'Failed to fetch pending reviews');

  @override
  Future<Result<void>> setReviewStatus(String id, String status) =>
      Result.guard<void>(() async {
        await _client
            .from('product_reviews')
            .update({'status': status}).eq('id', id);
      }, 'Failed to update review status');
}

AdminCoupon _couponFromRow(Map<String, dynamic> row) => AdminCoupon(
      id: row['id'] as String,
      code: (row['code'] as String?)?.toUpperCase() ?? '',
      discountMinor: (row['discount_minor'] as num?)?.toInt() ?? 0,
      active: row['active'] as bool? ?? false,
      description: row['description'] as String?,
    );
